#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Tiffany Cruz

# Short bio or description (displayed in the header)
description: Tiffany, a New York City native, holds a Masterâ€™s in English Literature from Mills College
  at Northeastern University. She focuses on race in British literature during the long eighteenth and
  nineteenth century. She also explores race in contemporary texts that adapt classic works, examining
  why there is such a strong interest in creating historical novels with these protagonist, and the significance
  of highlighting these people within these novels. She is particularly interested in the constructions
  of genre and how they shape both classical and modern texts, especially in relation to notions of race.
  This fascination extends to how literature influences societal values. This showcases the importance
  of these perspectives, and their contribution to literature during this historical period. She is currently
  a PhD student at Northeastern University getting her degree in English Literature. She also is a member
  of the United Confederation of Taino People.

# URL of your avatar or profile pic
avatar: https://raw.githubusercontent.com/[tiffanyfranchescacruz]/[tiffanyfranchescacruz].github.io/master/images/[IMG_1419.JPG].jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: cruz.ti@northeastern.edu
  github: tiffanyfranchescacruz
  instagram: tiffanyfranchescacruz
  
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.tiffanyfranchescacruz.com

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
    
    # Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
  
  # Use the following plug-ins
gems:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Include these files in the production _site
include: [_pages]

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
